### ISSUE TITLE
1.1.0 버전

### ISSUE THREAD

**Issue by Jeremy-Kr** [react-challengers/Codefolio#171]
## 시작 이전
- [x] recoil to jotai 논의(#197 )
- [x] Toast UI Editor VS Tiptab(#198 )
- [x] 이미지 업로드 library 선정(#205 )

### ERROR!
- [x] #199
- [x] #200

### 기능 추가
- [x] #202
- [x] #208
- [x] #203

### 리팩토링
- [x] #212
- [x] #213
- [x] #215
- [x] #217
- [x] #218
- [x] #214
- [x] #224 

### 스타일 및 수정

- [x] #219
```
- 풀스택
- 백엔드
- 프론트엔드
- 안드로이드
- iOS
- 플러터
- RN
- AI
- 빅데이터
```
- [x] #220
- [x] #222
- [x] #221
- [x] #223

### 스타일
- [x] #240
- [x] #241
- [x] #207
- [x] #242
- [x] #243
- [x] #244

### 배포 전 수정사항
- [x] #261

**Comment by Jeremy-Kr** [comment]
참고 링크들

- [Supabase 이미지 스토리지 관련](https://supabase.com/docs/guides/storage/image-transformations)
